# Generated by Django 5.2.7 on 2025-10-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(help_text="회의 대주제", max_length=50)),
                ("title", models.CharField(help_text="회의명", max_length=255)),
                ("summary", models.TextField(help_text="회의 요약")),
                ("meeting_date", models.DateField(help_text="회의 날짜")),
            ],
            options={
                "db_table": "meeting",
                "managed": True,
            },
        ),
    ]
